apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: jenkins-pvc 
  namespace: ops
spec: 
  accessModes:
    - ReadWriteOnce 
  storageClassName: standard #default storage class 
  resources: 
    requests: 
      storage: 10Gi