apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: ops

---

# Create the Jenkins Role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: ops
rules:
- apiGroups: ["apps"]  # For Deployments
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]  # Core API group
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["create", "delete", "get", "list", "patch", "set", "update", "watch"]


---

# Create the Jenkins Role Binding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: ops
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: ops
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io