apiVersion: v1
kind: Service
metadata:
  name: myserver-service
  namespace: myapp
spec:
  selector:
    app: myserver
  ports:
  - protocol: TCP
    port: 7272
    targetPort: 7272
    nodePort: 30007
  type: NodePort